name: yaru_settings
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  yaru: ^0.4.7
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
      ref: b16e8525747e0cc13a28d8553d9f3355ccacdec8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test: ^1.21.4

flutter:
  uses-material-design: true
