name: analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: analyze
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze
