name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  with-flutter-action:
    name: with-flutter-action
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: sudo apt -y install git curl cmake ninja-build make clang libgtk-3-dev pkg-config
      - run: flutter build linux -v
  
  with-flutter-snap:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo snap install flutter --classic
    - run: flutter build linux -v
      
